FROM ubuntu:jammy
RUN apt update && apt install python3 curl -y
RUN curl https://bootstrap.pypa.io/get-pip.py | python3
COPY . /app
RUN python3 -m pip install -r /app/requirements.txt
ENTRYPOINT ["python3"]
CMD ["/app/pythonsrc/main.py"]