---
# file: practice/1.kube-basics-lecture/1.8.service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: studa-studupa-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
      o4ko: malogo
  type: ClusterIP
...
